services:
  postgres:
    image: postgres:latest
    container_name: cavosh_postgres
    environment:
      POSTGRES_DB: cavoshDB
      POSTGRES_USER: cavosh
      POSTGRES_PASSWORD: cavosh123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cavosh_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cavosh.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db

volumes:
  pgdata:
