services:
  postgres:
    image: postgres:16-alpine
    container_name: cavosh_postgres
    environment:
      POSTGRES_DB: cavoshDB
      POSTGRES_USER: cavosh
      POSTGRES_PASSWORD: cavosh123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
